import type { MiniWorldChangeDefinition, MiniWorldChangeValue } from "@/types/miniWorldChange";

const COMMON_LOCATIONS = [
  "Ankrahmun",
  "Carlin",
  "Darashia",
  "Edron",
  "Liberty Bay",
  "Port Hope",
  "Svargrond",
  "Thais",
  "Venore",
  "Yalahar",
];

/**
 * The Mini World Changes tracked by the reference tool. Tibia exposes none of these
 * through a public API. Nine of them (source: "guide-npc") have an exact, documented
 * Guide NPC reply for every state (lib/parser/guideMessages.ts) and are populated only
 * by pasting a chat log in the import panel above — everything else (source: "manual")
 * has no reliable source and is directly editable.
 */
export const MINI_WORLD_CHANGE_DEFINITIONS: MiniWorldChangeDefinition[] = [
  {
    id: "fury-gate",
    label: "Fury Gate",
    shortLabel: "Fury Gate",
    emoji: "🔥",
    category: "gate",
    controlType: "toggle",
    source: "manual",
    description: "Whether the Fury Gate in Feyrist is currently open.",
  },
  {
    id: "hive",
    label: "Hive",
    shortLabel: "Hive",
    emoji: "👾",
    category: "hive",
    controlType: "stage",
    source: "guide-npc",
    description: "Current stage of the Hive invasion cycle.",
  },
  {
    id: "hive-east",
    label: "Hive — East",
    shortLabel: "Hive East",
    emoji: "👾",
    category: "hive",
    controlType: "toggle",
    source: "manual",
    description: "East hive status, when the cycle has a side-specific state.",
  },
  {
    id: "hive-west",
    label: "Hive — West",
    shortLabel: "Hive West",
    emoji: "👾",
    category: "hive",
    controlType: "toggle",
    source: "manual",
    description: "West hive status, when the cycle has a side-specific state.",
  },
  {
    id: "roshamuul",
    label: "Roshamuul",
    shortLabel: "Roshamuul",
    emoji: "🦇",
    category: "rotation",
    controlType: "toggle",
    source: "manual",
    description: "Whether the Roshamuul prison event is currently active.",
  },
  {
    id: "dream-courts",
    label: "Dream Courts Arena Boss",
    shortLabel: "Dream Courts",
    emoji: "👹",
    category: "arena",
    controlType: "boss",
    source: "manual",
    description: "Which boss is currently up in the Dream Courts arena.",
  },
  {
    id: "bibbys-bloodbath",
    label: "Bibby's Bloodbath",
    shortLabel: "Bibby's",
    emoji: "🏴‍☠️",
    category: "rotation",
    controlType: "location",
    source: "manual",
    description: "Current location of the Bibby's Bloodbath ship event.",
    suggestions: COMMON_LOCATIONS,
  },
  {
    id: "horestis-jars",
    label: "Horestis Jars",
    shortLabel: "Horestis",
    emoji: "🏺",
    category: "hunt",
    controlType: "stage",
    source: "guide-npc",
    description:
      "Horestis cycle near Ankrahmun: Inactive slumbering, Stage 1 risen (killable), Stage 2 killed/desecrated, Stage 3 curse ending.",
  },
  {
    id: "devovorga-essence",
    label: "Devovorga Essence",
    shortLabel: "Devovorga",
    emoji: "🧪",
    category: "rotation",
    controlType: "stage",
    source: "manual",
    description: "Current essence stage ahead of a Devovorga world event.",
  },
  {
    id: "deeplings",
    label: "Deeplings",
    shortLabel: "Deeplings",
    emoji: "🐙",
    category: "hunt",
    controlType: "stage",
    source: "guide-npc",
    description: "Current stage of the Deeplings invasion.",
  },
  {
    id: "sea-serpent",
    label: "Sea Serpent",
    shortLabel: "Sea Serpent",
    emoji: "🐍",
    category: "hunt",
    controlType: "stage",
    source: "guide-npc",
    description: "Current stage of the Sea Serpent event.",
  },
  {
    id: "big-iceberg",
    label: "Big Iceberg / Chakoya",
    shortLabel: "Iceberg",
    emoji: "🧊",
    category: "rotation",
    controlType: "stage",
    source: "manual",
    description: "Current phase of the Big Iceberg / Chakoya event.",
  },
  {
    id: "spirit-gate",
    label: "Spirit Gate",
    shortLabel: "Spirit Gate",
    emoji: "🌀",
    category: "gate",
    controlType: "location",
    source: "manual",
    description: "Where the current Spirit Gate is open — Darama, Ghostlands, or Vengoth.",
    suggestions: ["Darama", "Ghostlands", "Vengoth"],
  },
  {
    id: "nightmare-isles",
    label: "Nightmare Isles",
    shortLabel: "Nightmare Isles",
    emoji: "🌑",
    category: "rotation",
    controlType: "location",
    source: "manual",
    description: "Where the Nightmare Isles portal currently is, when accessible.",
    suggestions: [
      "Darama's northernmost coast",
      "River near Drefia",
      "Ankrahmun tar pits",
    ],
  },
  {
    id: "overhunting",
    label: "Overhunting Creature",
    shortLabel: "Overhunting",
    emoji: "⚔️",
    category: "hunt",
    controlType: "creature",
    source: "manual",
    description: "The creature currently flagged as overhunted on this world.",
  },
  {
    id: "goroma-volcano",
    label: "Goroma Volcano",
    shortLabel: "Goroma",
    emoji: "🌋",
    category: "rotation",
    controlType: "stage",
    source: "manual",
    description: "Current eruption stage of the Goroma volcano.",
  },
  {
    id: "darama-nomads",
    label: "Darama Nomads",
    shortLabel: "Darama",
    emoji: "🐫",
    category: "rotation",
    controlType: "location",
    source: "manual",
    description: "Current camp location of the Darama nomads.",
    suggestions: COMMON_LOCATIONS,
  },
  {
    id: "bored-witch",
    label: "Bored Witch",
    shortLabel: "Bored Witch",
    emoji: "🧙",
    category: "rotation",
    controlType: "toggle",
    source: "manual",
    description: "Whether Witch Wyda is currently bored (visitable) or not.",
  },
  {
    id: "noodles",
    label: "Noodles",
    shortLabel: "Noodles",
    emoji: "🍜",
    category: "rotation",
    controlType: "location",
    source: "manual",
    description: "Current location of the Noodles NPC.",
    suggestions: COMMON_LOCATIONS,
  },
  {
    id: "thais-kingsday",
    label: "Thais Kingsday",
    shortLabel: "Kingsday",
    emoji: "👑",
    category: "seasonal",
    controlType: "toggle",
    source: "manual",
    description: "Whether the Thais Kingsday festivities are currently active.",
  },
  {
    id: "thawing",
    label: "Thawing / Ice Flower",
    shortLabel: "Thawing",
    emoji: "❄️",
    category: "seasonal",
    controlType: "stage",
    source: "manual",
    description: "Current thaw stage of the Ice Flower event.",
  },
  {
    id: "spiders-nest",
    label: "Spider's Nest",
    shortLabel: "Spider's Nest",
    emoji: "🕷️",
    category: "hunt",
    controlType: "toggle",
    source: "manual",
    description: "Whether the Spider's Nest task area is currently active.",
  },
  {
    id: "horse-station",
    label: "Horse Station",
    shortLabel: "Horse Station",
    emoji: "🐴",
    category: "rotation",
    controlType: "location",
    source: "manual",
    description: "Current location of the traveling Horse Station.",
    suggestions: COMMON_LOCATIONS,
  },
  {
    id: "poacher-caves",
    label: "Poacher Caves",
    shortLabel: "Poacher Caves",
    emoji: "🏹",
    category: "hunt",
    controlType: "stage",
    source: "manual",
    description:
      "Dominance phase north of the Green Claw Swamp: Stage 1 game dominates, Stage 2 poachers dominate, Stage 3 vengeful ghost wolves dominate.",
  },
  {
    id: "jungle-camp",
    label: "Jungle Camp",
    shortLabel: "Jungle Camp",
    emoji: "🏕️",
    category: "hunt",
    controlType: "toggle",
    source: "manual",
    description: "Whether hunters and dworcs are fighting over Trapwood's holy grounds.",
  },
  {
    id: "grimvale",
    label: "Grimvale",
    shortLabel: "Grimvale",
    emoji: "🌲",
    category: "seasonal",
    controlType: "toggle",
    source: "manual",
    description: "Whether the full moon effect is active on the island of Grimvale.",
  },
  {
    id: "stampede",
    label: "Stampede",
    shortLabel: "Stampede",
    emoji: "🐘",
    category: "rotation",
    controlType: "toggle",
    source: "manual",
    description: "Whether Tiquanda's elephants have been stirred into a stampede.",
  },
  {
    id: "bank-robbery",
    label: "Bank Robbery",
    shortLabel: "Bank Robbery",
    emoji: "💰",
    category: "rotation",
    controlType: "toggle",
    source: "manual",
    description: "Whether banks in major coastal towns are currently being robbed.",
  },
  {
    id: "river-runs-deep",
    label: "River Runs Deep",
    shortLabel: "River Runs Deep",
    emoji: "🎣",
    category: "rotation",
    controlType: "toggle",
    source: "manual",
    description: "Whether the Zao Steppe river currently has more fish than usual.",
  },
  {
    id: "lumberjack",
    label: "Lumberjack",
    shortLabel: "Lumberjack",
    emoji: "🪓",
    category: "rotation",
    controlType: "toggle",
    source: "manual",
    description: "Whether the Queen's royal trees are currently being cut down.",
  },
  {
    id: "demon-war",
    label: "Demon War",
    shortLabel: "Demon War",
    emoji: "😈",
    category: "hunt",
    controlType: "stage",
    source: "guide-npc",
    description:
      "Shaburak vs. Askarak control of the Hero Cave complex — the winning faction goes in the detail note.",
  },
  {
    id: "twisted-waters",
    label: "Twisted Waters",
    shortLabel: "Twisted Waters",
    emoji: "💧",
    category: "hunt",
    controlType: "stage",
    source: "guide-npc",
    description: "Cleanliness of the great lake near Port Hope — Inactive clean, Stage 3 dirty & exhausted.",
  },
  {
    id: "awash",
    label: "Awash",
    shortLabel: "Awash",
    emoji: "⛏️",
    category: "hunt",
    controlType: "stage",
    source: "guide-npc",
    description: "Kazordoon mine-tunnel drainage cycle (Deepling Scouts access).",
  },
  {
    id: "steamship",
    label: "Steamship",
    shortLabel: "Steamship",
    emoji: "🚢",
    category: "rotation",
    controlType: "stage",
    source: "guide-npc",
    description: "Thais–Kazordoon steamship service status.",
  },
  {
    id: "overhunting-deer",
    label: "Overhunting — White Deer",
    shortLabel: "White Deer",
    emoji: "🦌",
    category: "hunt",
    controlType: "stage",
    source: "guide-npc",
    description: "White Deer / starving wolves population cycle near Ab'Dendriel.",
  },
  {
    id: "down-the-drain",
    label: "Down the Drain",
    shortLabel: "Down the Drain",
    emoji: "🌊",
    category: "rotation",
    controlType: "toggle",
    source: "manual",
    description: "Whether the river south of the outlaw camp is flooding a reachable island.",
  },
  {
    id: "chyllfroest",
    label: "Chyllfroest",
    shortLabel: "Chyllfroest",
    emoji: "🥶",
    category: "rotation",
    controlType: "toggle",
    source: "manual",
    description: "Whether the ice bridge from Svargrond to the frosty island is open.",
  },
];

export function createDefaultMiniWorldChangeValues(): Record<string, MiniWorldChangeValue> {
  const values: Record<string, MiniWorldChangeValue> = {};
  for (const def of MINI_WORLD_CHANGE_DEFINITIONS) {
    values[def.id] = {
      id: def.id,
      state: "unknown",
      detail: "",
      updatedAt: null,
    };
  }
  return values;
}
