import type { MiniWorldChangeDefinition, MiniWorldChangeValue } from "@/types/miniWorldChange";

const COMMON_LOCATIONS = [
  "Ankrahmun",
  "Carlin",
  "Darashia",
  "Edron",
  "Liberty Bay",
  "Port Hope",
  "Svargrond",
  "Thais",
  "Venore",
  "Yalahar",
];

/**
 * The Mini World Changes tracked by the reference tool. Tibia exposes none of these
 * through a public API — fansites traditionally read them off in-game board text — so
 * every value here is manual/local, seeded to "unknown" until the user fills it in.
 */
export const MINI_WORLD_CHANGE_DEFINITIONS: MiniWorldChangeDefinition[] = [
  {
    id: "fury-gate",
    label: "Fury Gate",
    shortLabel: "Fury Gate",
    emoji: "🔥",
    category: "gate",
    controlType: "toggle",
    description: "Whether the Fury Gate in Feyrist is currently open.",
  },
  {
    id: "hive",
    label: "Hive",
    shortLabel: "Hive",
    emoji: "👾",
    category: "hive",
    controlType: "stage",
    description: "Current stage of the Hive invasion cycle.",
  },
  {
    id: "hive-east",
    label: "Hive — East",
    shortLabel: "Hive East",
    emoji: "👾",
    category: "hive",
    controlType: "toggle",
    description: "East hive status, when the cycle has a side-specific state.",
  },
  {
    id: "hive-west",
    label: "Hive — West",
    shortLabel: "Hive West",
    emoji: "👾",
    category: "hive",
    controlType: "toggle",
    description: "West hive status, when the cycle has a side-specific state.",
  },
  {
    id: "roshamuul",
    label: "Roshamuul",
    shortLabel: "Roshamuul",
    emoji: "🦇",
    category: "rotation",
    controlType: "toggle",
    description: "Whether the Roshamuul prison event is currently active.",
  },
  {
    id: "dream-courts",
    label: "Dream Courts Arena Boss",
    shortLabel: "Dream Courts",
    emoji: "👹",
    category: "arena",
    controlType: "boss",
    description: "Which boss is currently up in the Dream Courts arena.",
  },
  {
    id: "bibbys-bloodbath",
    label: "Bibby's Bloodbath",
    shortLabel: "Bibby's",
    emoji: "🏴‍☠️",
    category: "rotation",
    controlType: "location",
    description: "Current location of the Bibby's Bloodbath ship event.",
    suggestions: COMMON_LOCATIONS,
  },
  {
    id: "horestis-jars",
    label: "Horestis Jars",
    shortLabel: "Horestis",
    emoji: "🏺",
    category: "hunt",
    controlType: "stage",
    description: "Progress of the Horestis jar-collecting task.",
  },
  {
    id: "devovorga-essence",
    label: "Devovorga Essence",
    shortLabel: "Devovorga",
    emoji: "🧪",
    category: "rotation",
    controlType: "stage",
    description: "Current essence stage ahead of a Devovorga world event.",
  },
  {
    id: "deeplings",
    label: "Deeplings",
    shortLabel: "Deeplings",
    emoji: "🐙",
    category: "hunt",
    controlType: "stage",
    description: "Current stage of the Deeplings invasion.",
  },
  {
    id: "sea-serpent",
    label: "Sea Serpent",
    shortLabel: "Sea Serpent",
    emoji: "🐍",
    category: "hunt",
    controlType: "stage",
    description: "Current stage of the Sea Serpent event.",
  },
  {
    id: "big-iceberg",
    label: "Big Iceberg / Chakoya",
    shortLabel: "Iceberg",
    emoji: "🧊",
    category: "rotation",
    controlType: "stage",
    description: "Current phase of the Big Iceberg / Chakoya event.",
  },
  {
    id: "spirit-gate",
    label: "Spirit Gate",
    shortLabel: "Spirit Gate",
    emoji: "🌀",
    category: "gate",
    controlType: "toggle",
    description: "Whether the Spirit Gate in Vengoth is currently open.",
  },
  {
    id: "nightmare-isles",
    label: "Nightmare Isles",
    shortLabel: "Nightmare Isles",
    emoji: "🌑",
    category: "rotation",
    controlType: "toggle",
    description: "Whether the Nightmare Isles are currently accessible.",
  },
  {
    id: "overhunting",
    label: "Overhunting Creature",
    shortLabel: "Overhunting",
    emoji: "⚔️",
    category: "hunt",
    controlType: "creature",
    description: "The creature currently flagged as overhunted on this world.",
  },
  {
    id: "goroma-volcano",
    label: "Goroma Volcano",
    shortLabel: "Goroma",
    emoji: "🌋",
    category: "rotation",
    controlType: "stage",
    description: "Current eruption stage of the Goroma volcano.",
  },
  {
    id: "darama-nomads",
    label: "Darama Nomads",
    shortLabel: "Darama",
    emoji: "🐫",
    category: "rotation",
    controlType: "location",
    description: "Current camp location of the Darama nomads.",
    suggestions: COMMON_LOCATIONS,
  },
  {
    id: "bored-witch",
    label: "Bored Witch",
    shortLabel: "Bored Witch",
    emoji: "🧙",
    category: "rotation",
    controlType: "location",
    description: "Current location of the Bored Witch.",
    suggestions: COMMON_LOCATIONS,
  },
  {
    id: "noodles",
    label: "Noodles",
    shortLabel: "Noodles",
    emoji: "🍜",
    category: "rotation",
    controlType: "location",
    description: "Current location of the Noodles NPC.",
    suggestions: COMMON_LOCATIONS,
  },
  {
    id: "thais-kingsday",
    label: "Thais Kingsday",
    shortLabel: "Kingsday",
    emoji: "👑",
    category: "seasonal",
    controlType: "toggle",
    description: "Whether the Thais Kingsday festivities are currently active.",
  },
  {
    id: "thawing",
    label: "Thawing / Ice Flower",
    shortLabel: "Thawing",
    emoji: "❄️",
    category: "seasonal",
    controlType: "stage",
    description: "Current thaw stage of the Ice Flower event.",
  },
  {
    id: "spiders-nest",
    label: "Spider's Nest",
    shortLabel: "Spider's Nest",
    emoji: "🕷️",
    category: "hunt",
    controlType: "toggle",
    description: "Whether the Spider's Nest task area is currently active.",
  },
  {
    id: "horse-station",
    label: "Horse Station",
    shortLabel: "Horse Station",
    emoji: "🐴",
    category: "rotation",
    controlType: "location",
    description: "Current location of the traveling Horse Station.",
    suggestions: COMMON_LOCATIONS,
  },
];

export function createDefaultMiniWorldChangeValues(): Record<string, MiniWorldChangeValue> {
  const values: Record<string, MiniWorldChangeValue> = {};
  for (const def of MINI_WORLD_CHANGE_DEFINITIONS) {
    values[def.id] = {
      id: def.id,
      state: "unknown",
      detail: "",
      updatedAt: null,
    };
  }
  return values;
}
